#!/bin/bash
# Convert music library to ogg

src=~/music/
dst=~/music.ogg/
aq=3
convert_types="flac"
copy_types="mp3 m4a"

cd $src

for filetype in $convert_types
do
for i in $(find -not -type d -iname "*.$filetype")
do

if [[ ! -a ${dst}${i%$filetype}ogg ]]
    then
    mkdir -p ${dst}${i%/*}
    avconv -i $i -c:a libvorbis -aq $aq ${dst}${i%$filetype}ogg
fi

done # list files loop
done # filetype loop

for filetype in $copy_types
do
for i in $(find -not -type d -iname "*.$filetype")
do

if [[ ! -a ${dst}${i} ]]
    then
    mkdir -p ${dst}${i%/*}
    cp -v $i ${dst}${i}
fi

done # list files loop
done # filetype loop
