#!/bin/bash
# Convert music library to ogg

src=~/music/
dst=~/music.ogg/

if [ ! -z $1 ]
then
  src=$1
fi

if [ ! -z $2 ]
then
  dst=$2
fi

aq=2
convert_types="flac mp3 m4a"
copy_types="jpg png"

cd $src

for filetype in $convert_types
do
  for i in $(find -name .git -prune -o -not -type d -iname "*.$filetype" -print)
  do

    if [[ ! -a ${dst}${i%$filetype}ogg ]]
      then
      mkdir -p ${dst}${i%/*}
      ffmpeg -i $i -vn -c:a libvorbis -aq $aq ${dst}${i%$filetype}ogg
    fi

  done # list files loop
done # filetype loop

for filetype in $copy_types
do
  for i in $(find -name .git -prune -o -not -type d -iname "*.$filetype" -print)
  do

    if [[ ! -a ${dst}${i} ]]
      then
      mkdir -p ${dst}${i%/*}
      cp -v $i ${dst}${i}
    fi

  done # list files loop
done # filetype loop
