#!/bin/bash
# Convert music library to mp3

src=~/music/
dst=~/music.mp3/

if [ ! -z $1 ]
then
  src=$1
fi

if [ ! -z $2 ]
then
  dst=$2
fi

convert_types="flac m4a"
copy_types="mp3 jpg png"

cd $src

for filetype in $convert_types
do
  for i in $(find -path ./.git -prune -o -not -type d -iname "*.$filetype")
  do

    if [[ ! -a ${dst}${i%$filetype}mp3 ]]
      then
      mkdir -p ${dst}${i%/*}
      ffmpeg -i $i -vn -c:a libmp3lame ${dst}${i%$filetype}mp3
    fi

  done # list files loop
done # filetype loop

for filetype in $copy_types
do
  for i in $(find -path ./.git -prune -o -not -type d -iname "*.$filetype")
  do

    if [[ ! -a ${dst}${i} ]]
      then
      mkdir -p ${dst}${i%/*}
      cp -v $i ${dst}${i}
    fi

  done # list files loop
done # filetype loop
