#!/bin/bash
# Convert flac music library to alac for itunes

src=~/music/
dst=~/music.alac/

cd $src

for i in $(find -not -type d -iname "*.flac")
do

if [[ ! -a ${dst}${i%flac}m4a ]]
    then
    mkdir -p ${dst}${i%/*}
    avconv -i $i -vn -c:a alac ${dst}${i%flac}m4a
fi

done
