#!/bin/bash

# Watch current directory for changes and auto commit them.

while [ true ]; do
inotifywait -r --exclude '^\./\.' -t 300 -e modify -e move -e delete .
sleep 10s
git add .
git commit -am "auto"
done
