#!/bin/bash

# install programs required for scripts to work, and other common software.

prereqs="git gitk git-annex libav-tools vorbis-tools flac id3v2 imagemagick gnupg2 pwgen exiv2 inotify-tools nfs-common xclip sqlite3 smartmontools postfix byobu openssh-server samba samba detox"

sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install $prereqs
