#! /bin/bash

# Forwards a port from remote server back to local machine.
# Useful for later accessing machine from home (server).

host="djones.co"

while [ true ]
do
date '+%F %T'
echo "Connecting."
ssh -NR 2222:localhost:22 $host
echo "Waiting one minute before reconnecting."
sleep 1m
done
