#! /bin/bash

# Forwards a port from remote server back to local machine.
# Useful for later accessing machine from home (server).

host="sol.djones.co"

while [ true ]
do
date
echo "Connecting."
ssh -R 2222:localhost:22 $host 'while :; do echo Keepalive: $(date); sleep 30s; done'
echo "Waiting one minute before reconnecting."
sleep 1m
done
