#! /bin/bash
# Rips CD to current directory and encodes to flac

cd-paranoia $@ -B
flac --best *.wav
ls
pwd
read -n1 -r -p "Press any key when discography.txt is ready."
echo
flac_build_tags
flac_import_tags
flac_rename_meta
detox *
echo "Don't forget to clean up!"
