#! /bin/bash
# Rips CD to current directory and encodes to flac

cd-paranoia $@ -B
sha1sum *.wav > wav.sha1sum
cd-paranoia $@ -B
sha1sum -c wav.sha1sum
read -n1 -r -p "Press any key if checksums are OK."
echo
flac --best *.wav
ls
pwd
read -n1 -r -p "Press any key when discography.txt is ready."
echo
flac_build_tags
flac_import_tags
flac_rename_meta
detox *
echo "Don't forget to clean up!"
