#! /bin/bash
# Rips CD to current directory and encodes to flac

cdparanoia $@ -B
flac --best *.wav
ls
pwd
read -n1 -r -p "Press any key when info.json is ready."
echo
flac_build_tags.py
flac_import_tags
flac_rename_meta
detox *
echo "Don't forget to clean up!"
